# Change these first
owner: ifrs-sertao # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Site IFRS
    url: https://ifrs.edu.br
#   - name: Moodle IFRS Osorio
#     url: https://moodle.osorio.ifrs.edu.br
  - name: Sistrac
    url: https://sistrac.osorio.ifrs.edu.br
#   - name: Eventos IFRS Osorio
#     url: https://eventos.osorio.ifrs.edu.br
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://github.com/ifrs-sertao/status/blob/master/Logo-Campus-Horizontal.png
  name: Status IFRS Osório
  introTitle: "**Upptime** é um serviço de monitoramento do IFRS Osório interamente hospedado no GitHub."
  introMessage: "DTI IFRS Osório"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
