# Change these first
owner: ifrs-sertao # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Site IFRS
    url: https://ifrs.edu.br/sertao
    

  - name: Moodle Sertão
    url: https://moodle.sertao.ifrs.edu.br
    __dangerous__disable_verify_peer: true
    expectedStatusCodes:
      - 200
    assignees:
      - tiagojferreira-IFRS
    
  - name: Campus Digital
    url: https://campusdigital.sertao.ifrs.edu.br
    
  - name: Sistemas de Chamados
    url: https://suporte.sertao.ifrs.edu.br
    __dangerous__disable_verify_peer: true
    expectedStatusCodes:
      - 200
    assignees:
      - tiagojferreira-IFRS
      
  - name: CEUA
    url: http://ceua.sertao.ifrs.edu.br




status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://raw.githubusercontent.com/ifrs-sertao/status/master/img/logos/Instituto_Federal_Sertao_Refeito13.png
  name: Status IFRS Sertão
  introTitle: "**Upptime** é um serviço de monitoramento do IFRS Sertão interamente hospedado no GitHub."
  introMessage: "O monitoramento externo permite verificar se os serviços gerenciados pela CTI IFRS Campus Sertão estão online. Sites offiline aparecerão no topo
  em vermelho. Logo abaixo, site online em verde com opções de visualização das últimas 24 horas, 7 dias e assim por diante."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
#   theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
